version: 2.1

workflows:
  version: 2
  example-1:
    jobs:
      - example-1

jobs:
  example-1:
    machine:
      docker_layer_caching: false
      image: ubuntu-2204:2022.04.1
    steps:
      - checkout
      - run:
          name: "smoke-test-ubuntu"
          command: make smoke-test-ubuntu
